module Euler.Problem29

(* How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100
and 2 ≤ b ≤ 100?*)

let solution =
    [ for a in 2I..100I do
        for b in 2..100 do
            yield a**b]
    |> List.distinct
    |> List.length
